[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Override the standard Arduino core with the Bluepad32-enabled version
platform_packages = 
    framework-arduinoespressif32 @ https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

; ── Board config ──────────────────────────────────────
board_build.mcu        = esp32
board_build.f_cpu      = 240000000L
board_build.partitions = huge_app.csv

; ── Upload & Monitor ──────────────────────────────────
monitor_speed  = 115200
upload_speed   = 921600
monitor_filters = esp32_exception_decoder

; ── Unit Testing ─────────────────────────────────────
test_framework = unity
test_build_src = true
test_speed     = 115200

; ── Build Flags ───────────────────────────────────────
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -std=gnu++17
    -Os



lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11

; ──────── Handlers ────────
; IMU:       Wire.h (raw I2C)
; GPS:       HardwareSerial (NMEA parser)
; FreeRTOS:  Bundled with ESP-IDF


